### ISSUE TITLE
Name not found and errors reading from name store

### ISSUE THREAD

**Issue by srobb1** [GMOD/jbrowse#1171]
Hello,
I am using 1.15.1-dev. I updated JBrowse but kept my previous data directory with all my data, conf files, and indices. When I search for a name in the search box I get a pop up that says "Not found: hdac10" and one that says "Error reading from name store."  

I get these errors in the console:
```
instrumentation.js:23 Error: This deferred has already been resolved
    at complete (Deferred.js:164)
    at Array.concat.dojo.Deferred.resolve.callback (Deferred.js:248)
    at lang.js:383
    at notify (Deferred.js:187)
    at complete (Deferred.js:168)
    at Array.concat.dojo.Deferred.resolve.callback (Deferred.js:248)
    at notify (Deferred.js:196)
    at complete (Deferred.js:168)
    at Array.concat.dojo.Deferred.resolve.callback (Deferred.js:248)
    at notify (Deferred.js:204) "Error: This deferred has already been resolved
    at complete (https://genomesdev.stowers.org/jbrowse/dist/3.bundle.js:58614:11)
    at Array.concat.dojo.Deferred.resolve.callback (https://genomesdev.stowers.org/jbrowse/dist/3.bundle.js:58698:4)
    at https://genomesdev.stowers.org/jbrowse/dist/3.bundle.js:3946:45
    at notify (https://genomesdev.stowers.org/jbrowse/dist/3.bundle.js:58637:23)
    at complete (https://genomesdev.stowers.org/jbrowse/dist/3.bundle.js:58618:4)
    at Array.concat.dojo.Deferred.resolve.callback (https://genomesdev.stowers.org/jbrowse/dist/3.bundle.js:58698:4)
    at notify (https://genomesdev.stowers.org/jbrowse/dist/3.bundle.js:58646:69)
    at complete (https://genomesdev.stowers.org/jbrowse/dist/3.bundle.js:58618:4)
    at Array.concat.dojo.Deferred.resolve.callback (https://genomesdev.stowers.org/jbrowse/dist/3.bundle.js:58698:4)
    at notify (https://genomesdev.stowers.org/jbrowse/dist/3.bundle.js:58654:25)"

Browser.js:2601 TypeError: Cannot read property 'toString' of undefined
    at fastDeclareClass.localeCompare (Location.js:59)
    at Hash.js:92
    at Array.sort (/jbrowse/native)
    at Object._makeResults (Hash.js:90)
    at Hash.js:153
    at notify (Deferred.js:187)
    at complete (Deferred.js:168)
    at Array.concat.dojo.Deferred.resolve.callback (Deferred.js:248)
    at notify (Deferred.js:196)
    at complete (Deferred.js:168)
```

When I try to generate-names (in case something is wrong with my indexed names) I get this error:
```
syntax error in /var/other_data/JBrowse-1.15.1-dev/data/Nfur_v10/trackList.json: malformed JSON string, neither tag, array, object, number, string or atom, at character offset 18829 (before "],\n   "names" : {\n...") at /var/other_data/JBrowse-1.15.1-dev/bin/../src/perl5/Bio/JBrowse/ConfigurationManager.pm line 32.
 at /var/other_data/JBrowse-1.15.1-dev/bin/../src/perl5/Bio/JBrowse/ConfigurationManager.pm line 7.
	Bio::JBrowse::ConfigurationManager::__ANON__('malformed JSON string, neither tag, array, object, number, st...') called at /var/other_data/JBrowse-1.15.1-dev/bin/../src/perl5/Bio/JBrowse/ConfigurationManager.pm line 32
	eval {...} called at /var/other_data/JBrowse-1.15.1-dev/bin/../src/perl5/Bio/JBrowse/ConfigurationManager.pm line 32
	Bio::JBrowse::ConfigurationManager::slurpJSON('/var/other_data/JBrowse-1.15.1-dev/data/Nfur_v10/trackList.json') called at /var/other_data/JBrowse-1.15.1-dev/bin/../src/perl5/Bio/JBrowse/ConfigurationManager.pm line 145
	Bio::JBrowse::ConfigurationManager::_load_include('Bio::JBrowse::ConfigurationManager=HASH(0x1eda920)', 'HASH(0x1eda998)', 'data/Nfur_v10/') called at /var/other_data/JBrowse-1.15.1-dev/bin/../src/perl5/Bio/JBrowse/ConfigurationManager.pm line 71
	Bio::JBrowse::ConfigurationManager::_load_includes('Bio::JBrowse::ConfigurationManager=HASH(0x1eda920)', 'HASH(0x1c3d5b0)') called at /var/other_data/JBrowse-1.15.1-dev/bin/../src/perl5/Bio/JBrowse/ConfigurationManager.pm line 41
	Bio::JBrowse::ConfigurationManager::get_final_config('Bio::JBrowse::ConfigurationManager=HASH(0x1eda920)') called at /var/other_data/JBrowse-1.15.1-dev/bin/../src/perl5/GenomeDB.pm line 286
	GenomeDB::trackList('GenomeDB=HASH(0x14b8848)') called at /var/other_data/JBrowse-1.15.1-dev/bin/../src/perl5/Bio/JBrowse/Cmd/IndexNames.pm line 82
	Bio::JBrowse::Cmd::IndexNames::run('Bio::JBrowse::Cmd::IndexNames=HASH(0x12efb68)') called at bin/generate-names.pl line 8
 at /var/other_data/JBrowse-1.15.1-dev/bin/../src/perl5/Bio/JBrowse/ConfigurationManager.pm line 7.
	Bio::JBrowse::ConfigurationManager::__ANON__('syntax error in /var/other_data/JBrowse-1.15.1-dev/data/Nfur_...') called at /var/other_data/JBrowse-1.15.1-dev/bin/../src/perl5/Bio/JBrowse/ConfigurationManager.pm line 33
	Bio::JBrowse::ConfigurationManager::slurpJSON('/var/other_data/JBrowse-1.15.1-dev/data/Nfur_v10/trackList.json') called at /var/other_data/JBrowse-1.15.1-dev/bin/../src/perl5/Bio/JBrowse/ConfigurationManager.pm line 145
	Bio::JBrowse::ConfigurationManager::_load_include('Bio::JBrowse::ConfigurationManager=HASH(0x1eda920)', 'HASH(0x1eda998)', 'data/Nfur_v10/') called at /var/other_data/JBrowse-1.15.1-dev/bin/../src/perl5/Bio/JBrowse/ConfigurationManager.pm line 71
	Bio::JBrowse::ConfigurationManager::_load_includes('Bio::JBrowse::ConfigurationManager=HASH(0x1eda920)', 'HASH(0x1c3d5b0)') called at /var/other_data/JBrowse-1.15.1-dev/bin/../src/perl5/Bio/JBrowse/ConfigurationManager.pm line 41
	Bio::JBrowse::ConfigurationManager::get_final_config('Bio::JBrowse::ConfigurationManager=HASH(0x1eda920)') called at /var/other_data/JBrowse-1.15.1-dev/bin/../src/perl5/GenomeDB.pm line 286
	GenomeDB::trackList('GenomeDB=HASH(0x14b8848)') called at /var/other_data/JBrowse-1.15.1-dev/bin/../src/perl5/Bio/JBrowse/Cmd/IndexNames.pm line 82
	Bio::JBrowse::Cmd::IndexNames::run('Bio::JBrowse::Cmd::IndexNames=HASH(0x12efb68)') called at bin/generate-names.pl line 8
```

I am not sure what is wrong with my json syntax. These config files worked with my 1.12.3 install. 
Here is my names block in my trackList.conf
```
   ],
   "names" : {
      "url" : "names/",
      "type" : "Hash"
   },
```

Thank you for your help,
Sofia

**Comment by cmdcolin** [comment]
The JSON related error when you ran re-indexing does suggest some sort of syntax error in the JSON. Some additional checks of the JSON were added in recent versions so this was why maybe this error is new. You could check it in https://jsonlint.com/ or share it here, it says maybe it's before the snippet that you posted.

Nevertheless, the error with the name store is probably not related to the json validation and is concerning...I was looking to at least one error kind of similar here https://github.com/GMOD/jbrowse/issues/1171 I guess any more details or a live instance or data dump of the jbrowse data directory could possibly help!

**Comment by cmdcolin** [comment]
Any update on this @srobb1? Sample instance or data dump would be awesome :)

**Comment by srobb1** [comment]
Hi @cmdcolin. Thanks for checking in. Yes. I had many trailing commas.  I cleaned those up. When I try to search for a name, I get the same "Not Found" error. When I try to run generate-names. It runs but only for one of the many tracks in the list for the --tracks option. I am currently trying to reload all my tracks to see if this helps. I will get back to you once my tracks have all loaded and I try again to index the names with generate-names. If this does not work, then I will looking into how to do a data dump.

**Comment by srobb1** [comment]
After reloading tracks with flatfile-to-json.pl and then using generate-names.pl everything seems to be working as expected.

**Comment by cmdcolin** [comment]
Sweet! It is always surprising to see something happen like that, but glad it is fixed. I guess we'll close for now :)
