### ISSUE TITLE
TypeError: Cannot read property 'basesPerBin' of undefined

### ISSUE THREAD

**Issue by harika91** [GMOD/jbrowse#1327]
JBrowse Version: 1.16.3
When a track has very few variants example : 2 positions in a sequence,
below error is seen on the Javascript console.
Jbrowse gets struck "loading" the track
![error](https://user-images.githubusercontent.com/33872527/53826842-3b2ff900-3f3f-11e9-8ecd-8f72c37f3200.PNG)

Error:
instrumentation.js:23 TypeError: Cannot read property 'basesPerBin' of undefined
    at NCList.js:189
    at signalListener (Deferred.js:37)
    at signalWaiting (Deferred.js:28)
    at Deferred.resolve (Deferred.js:192)
    at Object._handleTrackInfo (NCList.js:128)
    at NCList.js:90
    at signalListener (Deferred.js:37)
    at signalWaiting (Deferred.js:28)
    at Deferred.resolve (Deferred.js:192)
    at signalDeferred (Deferred.js:81) "TypeError: Cannot read property 'basesPerBin' of undefined
    at https://dev.rgd.mcw.edu/jbrowse/src/JBrowse/Store/SeqFeature/NCList.js:189:60
    at signalListener (https://dev.rgd.mcw.edu/jbrowse/src/dojo/Deferred.js:37:21)
    at signalWaiting (https://dev.rgd.mcw.edu/jbrowse/src/dojo/Deferred.js:28:4)
    at Deferred.resolve (https://dev.rgd.mcw.edu/jbrowse/src/dojo/Deferred.js:192:5)
    at Object._handleTrackInfo (https://dev.rgd.mcw.edu/jbrowse/src/JBrowse/Store/SeqFeature/NCList.js:128:29)
    at https://dev.rgd.mcw.edu/jbrowse/src/JBrowse/Store/SeqFeature/NCList.js:90:33
    at signalListener (https://dev.rgd.mcw.edu/jbrowse/src/dojo/Deferred.js:37:21)
    at signalWaiting (https://dev.rgd.mcw.edu/jbrowse/src/dojo/Deferred.js:28:4)
    at Deferred.resolve (https://dev.rgd.mcw.edu/jbrowse/src/dojo/Deferred.js:192:5)
    at signalDeferred (https://dev.rgd.mcw.edu/jbrowse/src/dojo/Deferred.js:81:15)
    ----------------------------------------
    rejected at signalDeferred (https://dev.rgd.mcw.edu/jbrowse/src/dojo/Deferred.js:84:15)
    at signalListener (https://dev.rgd.mcw.edu/jbrowse/src/dojo/Deferred.js:55:5)
    at signalWaiting (https://dev.rgd.mcw.edu/jbrowse/src/dojo/Deferred.js:28:4)
    at Deferred.resolve (https://dev.rgd.mcw.edu/jbrowse/src/dojo/Deferred.js:192:5)
    at Object._handleTrackInfo (https://dev.rgd.mcw.edu/jbrowse/src/JBrowse/Store/SeqFeature/NCList.js:128:29)
    at https://dev.rgd.mcw.edu/jbrowse/src/JBrowse/Store/SeqFeature/NCList.js:90:33
    at signalListener (https://dev.rgd.mcw.edu/jbrowse/src/dojo/Deferred.js:37:21)
    at signalWaiting (https://dev.rgd.mcw.edu/jbrowse/src/dojo/Deferred.js:28:4)
    at Deferred.resolve (https://dev.rgd.mcw.edu/jbrowse/src/dojo/Deferred.js:192:5)
    at signalDeferred (https://dev.rgd.mcw.edu/jbrowse/src/dojo/Deferred.js:81:15)
    ----------------------------------------
Error
    at Deferred.then.promise.then (https://dev.rgd.mcw.edu/jbrowse/src/dojo/Deferred.js:252:24)
    at Object.getRegionFeatureDensities (https://dev.rgd.mcw.edu/jbrowse/src/JBrowse/Store/SeqFeature/NCList.js:147:14)
    at Object.fillHistograms (https://dev.rgd.mcw.edu/jbrowse/src/JBrowse/View/Track/CanvasFeatures.js:374:24)
    at Object.<anonymous> (https://dev.rgd.mcw.edu/jbrowse/src/JBrowse/View/Track/CanvasFeatures.js:249:26)
    at https://dev.rgd.mcw.edu/jbrowse/src/dojo/_base/lang.js:385:55
    at https://dev.rgd.mcw.edu/jbrowse/src/JBrowse/Store/SeqFeature/NCList.js:133:46
    at signalListener (https://dev.rgd.mcw.edu/jbrowse/src/dojo/Deferred.js:37:21)
    at signalWaiting (https://dev.rgd.mcw.edu/jbrowse/src/dojo/Deferred.js:28:4)
    at Deferred.resolve (https://dev.rgd.mcw.edu/jbrowse/src/dojo/Deferred.js:192:5)
    at Object._handleTrackInfo (https://dev.rgd.mcw.edu/jbrowse/src/JBrowse/Store/SeqFeature/NCList.js:128:29)"

**Comment by cmdcolin** [comment]
If you have sample data that could help, the track config you are using also

**Comment by harika91** [comment]
Configs used for the track:

--clientConfig "{ \"className\" : \"feature\", \"color\" : \"function( feature ) { var pred = feature.get( \\\"polypred\\\" ); if( pred == null ) pred = \\\"NA\\\"; else pred = decodeURIComponent( pred.toString() ).split( \\\",\\\" )[ 0 ].split( \\\"||\\\" )[ 4 ]; switch( pred ) { case \\\"probably damaging\\\": return \\\"#DF255A\\\"; case \\\"possibly damaging\\\": return \\\"#C4C400\\\";  } }\", \"label\" : \"symbol,name\", \"featureScale\" : 0.0001, \"description\" : \"\" }" 

--config "{ \"category\" : \"Variants/Damaging Variants\", \"histograms\" : { \"binsPerBlock\" : 25, \"color\" : \"#6600CC\" }, \"onClick\" : { \"iconClass\" : \"dijitIconDatabase\", \"content\" : \"<iframe src=\\\"/rgdweb/front/detail_gbrowse.html?vid={name}&mapKey=${mapKey}\\\" frameborder='0' marginheight='0' scrolling='yes' width='680' height='315'></iframe>\", \"action\" : \"contentDialog\", \"title\" : \"<center>RGD Strain-Specific Data for Variant #{name}</center>\" }, \"menuTemplate\" : [ { \"iconClass\" : \"dijitIconDatabase\", \"content\" : \"<iframe src=\\\"/rgdweb/front/detail_gbrowse.html?vid={name}&mapKey=${mapKey}\\\" frameborder='0' marginheight='0' scrolling='yes' width='680' height='315'></iframe>\", \"action\" : \"contentDialog\", \"title\" : \"<center>RGD Strain-Specific Data for Variant #{name}</center>\", \"label\" : \"View RGD Details\" }, { \"label\" : \"Highlight this feature\" } ] }"
     
[names.txt](https://github.com/GMOD/jbrowse/files/2932632/names.txt)
[tracksData.txt](https://github.com/GMOD/jbrowse/files/2932650/tracksData.txt)

**Comment by cmdcolin** [comment]
If you need to get this working "today" I would probably recommend removing featureScale, it is probably forcing histograms to display when none exist causing this error. Probably jbrowse should have some better handling for this though

**Comment by harika91** [comment]
That worked for now
