### ISSUE TITLE
jasmine tabix tests failing on chrome

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse#965]
At e5caef656e539e1cb5ad83dd6ae5af63f0f95c41:

![image](https://user-images.githubusercontent.com/73749/35490688-4a392e50-0456-11e8-9ca5-b72a11dee9bc.png)

Git bisect yields d29447a104eab489b3e03e6186cd60ad5148d8b4 as the first bad commit for this failure.

**Comment by rbuels** [comment]
```
Error: Expected 0 to equal 8.
    at new jasmine.ExpectationResult (http://localhost:8080/tests/js_tests/lib/jasmine-1.2.0/jasmine.js:102:32)
    at matchersClass.toEqual (http://localhost:8080/tests/js_tests/lib/jasmine-1.2.0/jasmine.js:1194:29)
    at jasmine.Spec.<anonymous> (http://localhost:8080/tests/js_tests/spec/TabixIndexedFile.spec.js:44:45)
    at jasmine.Block.execute (http://localhost:8080/tests/js_tests/lib/jasmine-1.2.0/jasmine.js:1024:15)
    at jasmine.Queue.next_ (http://localhost:8080/tests/js_tests/lib/jasmine-1.2.0/jasmine.js:2025:31)
    at onComplete (http://localhost:8080/tests/js_tests/lib/jasmine-1.2.0/jasmine.js:2021:18)
    at jasmine.WaitsForBlock.execute (http://localhost:8080/tests/js_tests/lib/jasmine-1.2.0/jasmine.js:2505:5)
    at http://localhost:8080/tests/js_tests/lib/jasmine-1.2.0/jasmine.js:2519:12
```

**Comment by rbuels** [comment]
They pass in firefox, phantom, and safari, which could be a clue.

**Comment by rbuels** [comment]
And then the failure it disappeared when I cleared my chrome cache and ran it again. Sigh.
